/**:
  ros__parameters:
    use_sim_time: false
    
    # Enhanced BT Navigator with multi-sensor support
    bt_navigator:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      odom_topic: /orbibot/odometry/enhanced  # Use enhanced localization
      bt_loop_duration: 10
      default_server_timeout: 20
      action_server_result_timeout: 900.0
      navigators: ["navigate_to_pose", "navigate_through_poses"]
      navigate_to_pose:
        plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
      navigate_through_poses:
        plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"
      plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node

    # Enhanced Controller Server for mecanum drive
    controller_server:
      use_sim_time: false
      controller_frequency: 30.0  # Increased for better responsiveness
      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.001  # Lower threshold for mecanum
      min_theta_velocity_threshold: 0.001
      failure_tolerance: 0.3
      progress_checker_plugin: "progress_checker"
      goal_checker_plugins: ["general_goal_checker"] 
      controller_plugins: ["FollowPath"]

      # Progress checker parameters
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.3  # Reduced for better sensitivity
        movement_time_allowance: 15.0  # Increased for complex maneuvers
      
      # Goal checker parameters
      general_goal_checker:
        stateful: True
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.2   # Tighter tolerance
        yaw_goal_tolerance: 0.2  # Tighter tolerance

      # Enhanced DWB Controller for mecanum wheels
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        debug_trajectory_details: False
        min_vel_x: -0.4      # Increased range for mecanum
        min_vel_y: -0.4      # Full y-axis movement
        max_vel_x: 0.4
        max_vel_y: 0.4
        max_vel_theta: 1.2   # Increased rotation speed
        min_speed_xy: 0.0
        max_speed_xy: 0.6    # Increased max speed
        min_speed_theta: 0.0
        acc_lim_x: 2.0
        acc_lim_y: 2.0       # Mecanum y-axis acceleration
        acc_lim_theta: 3.0
        decel_lim_x: -2.5
        decel_lim_y: -2.5
        decel_lim_theta: -3.2
        vx_samples: 25       # Increased samples for better planning
        vy_samples: 15       # Y-axis samples for mecanum
        vtheta_samples: 30   # More rotation samples
        sim_time: 2.0        # Increased prediction time
        linear_granularity: 0.05
        angular_granularity: 0.025
        transform_tolerance: 0.2
        xy_goal_tolerance: 0.2
        trans_stopped_velocity: 0.15
        short_circuit_trajectory_evaluation: True
        stateful: True
        critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "PathProgressCritic"]
        BaseObstacle.scale: 0.02
        PathAlign.scale: 32.0
        PathAlign.forward_point_distance: 0.1
        GoalAlign.scale: 24.0
        GoalAlign.forward_point_distance: 0.1
        PathDist.scale: 32.0
        GoalDist.scale: 24.0
        RotateToGoal.scale: 32.0
        RotateToGoal.slowing_factor: 5.0
        RotateToGoal.lookahead_time: -1.0
        PathProgressCritic.scale: 10.0

    # Enhanced Local Costmap with multi-sensor input
    local_costmap:
      local_costmap:
        use_sim_time: false
        global_frame: odom
        plugin_names: ["voxel_layer", "inflation_layer", "depth_layer"]
        plugin_types: ["nav2_costmap_2d::VoxelLayer", "nav2_costmap_2d::InflationLayer", "nav2_costmap_2d::VoxelLayer"]
        rolling_window: true
        width: 4         # Increased size for better lookahead
        height: 4
        resolution: 0.05
        robot_radius: 0.22
        plugins: ["voxel_layer", "inflation_layer", "depth_layer"]
        
        # Enhanced inflation for safety
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.6  # Increased for safety
          
        # LIDAR-based obstacle detection
        voxel_layer:
          plugin: "nav2_costmap_2d::VoxelLayer"
          enabled: True
          publish_voxel_map: True
          origin_z: 0.0
          z_resolution: 0.05
          z_voxels: 16
          max_obstacle_height: 2.0
          mark_threshold: 0
          observation_sources: scan
          scan:
            topic: /scan
            max_obstacle_height: 2.0
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 3.5
            raytrace_min_range: 0.0
            obstacle_max_range: 3.0
            obstacle_min_range: 0.0
            
        # Depth camera-based obstacle detection
        depth_layer:
          plugin: "nav2_costmap_2d::VoxelLayer"
          enabled: True
          publish_voxel_map: False
          origin_z: 0.0
          z_resolution: 0.1
          z_voxels: 10
          max_obstacle_height: 1.5
          mark_threshold: 0
          observation_sources: depth_scan
          depth_scan:
            topic: /depth_scan
            max_obstacle_height: 1.5
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 2.0
            raytrace_min_range: 0.0
            obstacle_max_range: 1.8
            obstacle_min_range: 0.4
            
        always_send_full_costmap: True

    # Enhanced Global Costmap
    global_costmap:
      global_costmap:
        use_sim_time: false
        robot_radius: 0.22
        update_frequency: 1.0
        publish_frequency: 1.0
        global_frame: map
        robot_base_frame: base_link
        resolution: 0.05
        track_unknown_space: true
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        
        # Static map layer
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: True
          
        # Dynamic obstacle layer
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: scan depth_scan
          scan:
            topic: /scan
            max_obstacle_height: 2.0
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 4.0
            raytrace_min_range: 0.0
            obstacle_max_range: 3.5
            obstacle_min_range: 0.0
          depth_scan:
            topic: /depth_scan
            max_obstacle_height: 1.5
            clearing: True
            marking: True
            data_type: "LaserScan"
            raytrace_max_range: 2.5
            raytrace_min_range: 0.0
            obstacle_max_range: 2.0
            obstacle_min_range: 0.4
            
        # Enhanced inflation
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.8  # Larger global inflation
          
        always_send_full_costmap: True

    # Map Server Parameters
    map_server:
      use_sim_time: false
      yaml_filename: ""

    # Map Saver Parameters
    map_saver:
      use_sim_time: false
      save_map_timeout: 5.0
      free_thresh_default: 0.25
      occupied_thresh_default: 0.65
      map_subscribe_transient_local: True

    # Enhanced Planner Server
    planner_server:
      use_sim_time: false
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner"
        tolerance: 0.3      # Reduced tolerance for precision
        use_astar: true     # A* for better paths
        allow_unknown: true

    # Smoother Server Parameters
    smoother_server:
      use_sim_time: false
      smoother_plugins: ["simple_smoother"]
      simple_smoother:
        plugin: "nav2_smoother::SimpleSmoother"
        tolerance: 1.0e-10
        max_its: 1000
        do_refinement: True

    # Enhanced Behavior Server
    behavior_server:
      use_sim_time: false
      costmap_topic: local_costmap/costmap_raw
      footprint_topic: local_costmap/published_footprint
      cycle_frequency: 10.0
      behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
      spin:
        plugin: "nav2_behaviors/Spin"
      backup:
        plugin: "nav2_behaviors/BackUp"
      drive_on_heading:
        plugin: "nav2_behaviors/DriveOnHeading"
      wait:
        plugin: "nav2_behaviors/Wait"
      assisted_teleop:
        plugin: "nav2_behaviors/AssistedTeleop"
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.1
      simulate_ahead_time: 2.0
      max_rotational_vel: 1.2    # Increased for faster recovery
      min_rotational_vel: 0.4
      rotational_acc_lim: 3.2

    # Waypoint Follower Parameters
    waypoint_follower:
      use_sim_time: false
      loop_rate: 20
      stop_on_failure: false
      waypoint_task_executor_plugin: "wait_at_waypoint"
      wait_at_waypoint:
        plugin: "nav2_waypoint_follower::WaitAtWaypoint"
        enabled: True
        waypoint_pause_duration: 200

    # Enhanced Velocity Smoother
    velocity_smoother:
      use_sim_time: false
      smoothing_frequency: 30.0   # Increased for responsiveness
      scale_velocities: False
      feedback: "OPEN_LOOP"
      max_velocity: [0.6, 0.6, 2.0]     # Increased for mecanum
      min_velocity: [-0.6, -0.6, -2.0]
      max_accel: [2.0, 2.0, 3.0]
      max_decel: [-2.5, -2.5, -3.2]
      odom_topic: "/orbibot/odometry/enhanced"  # Use enhanced odometry
      odom_duration: 0.1
      deadband_velocity: [0.0, 0.0, 0.0]
      velocity_timeout: 1.0