/**:
  ros__parameters:
    # RealSense D435 Configuration
    device_type: d435
    serial_no: ""
    usb_port_id: ""
    device_type: ""
    
    # Camera settings
    camera_name: camera
    camera_namespace: ""
    
    # Enable/disable streams
    enable_color: true
    enable_depth: true
    enable_infra1: false
    enable_infra2: false
    enable_fisheye: false
    enable_confidence: false
    enable_accel: false
    enable_gyro: false
    
    # Color stream settings
    color_width: 640
    color_height: 480
    color_fps: 30
    color_format: RGB8
    
    # Depth stream settings
    depth_width: 640
    depth_height: 480
    depth_fps: 30
    depth_format: Z16
    
    # Infrared stream settings
    infra_width: 640
    infra_height: 480
    infra_fps: 30
    infra_format: Y8
    
    # Processing options
    align_depth: true
    align_depth_to: color
    enable_pointcloud: true
    pointcloud_texture_stream: RS2_STREAM_COLOR
    pointcloud_texture_index: 0
    
    # Filters
    filters: "spatial,temporal,decimation"
    
    # Spatial filter
    spatial_filter.enable: true
    spatial_filter.smooth_alpha: 0.5
    spatial_filter.smooth_delta: 20.0
    spatial_filter.magnitude: 2.0
    spatial_filter.hole_fill: 0.0
    
    # Temporal filter
    temporal_filter.enable: true
    temporal_filter.smooth_alpha: 0.4
    temporal_filter.smooth_delta: 20.0
    temporal_filter.persistence_control: 3.0
    
    # Decimation filter
    decimation_filter.enable: true
    decimation_filter.filter_magnitude: 2.0
    
    # Frame IDs
    base_frame_id: camera_link
    depth_frame_id: camera_depth_frame
    color_frame_id: camera_color_frame
    infra1_frame_id: camera_infra1_frame
    infra2_frame_id: camera_infra2_frame
    
    # TF publishing
    publish_tf: true
    tf_publish_rate: 0.0  # 0 = static
    
    # Diagnostics
    diagnostics_period: 0.0  # 0 = disabled
    
    # Quality settings
    depth_quality: 1  # 0=low, 1=medium, 2=high
    color_quality: 1  # 0=low, 1=medium, 2=high
    
    # Auto exposure
    color_auto_exposure: true
    depth_auto_exposure: true