orbibot_control_manager:
  ros__parameters:
    # Robot physical parameters (must match hardware_params.yaml)
    robot:
      wheel_radius: 0.05            # m (50mm radius, 100mm diameter)
      wheel_separation_x: 0.18      # m (180mm front-back)
      wheel_separation_y: 0.30      # m (300mm left-right)
    
    # Control settings
    control:
      publish_tf: true              # Publish odom→base_link transform
      odom_frame: "odom"            # Odometry frame name
      base_frame: "base_link"       # Robot base frame name
    
    # Monitoring settings
    monitor:
      cmd_timeout_warning: 5.0      # seconds - warn if no cmd_vel for this long
      system_check_rate: 10.0       # Hz - system health check rate