<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="orbibot">

  <!-- Robot Parameters -->
  <xacro:property name="PI" value="3.14159265359"/>
  
  <!-- Wheel specifications -->
  <xacro:property name="wheel_radius" value="0.05"/>           <!-- 100mm diameter = 50mm radius -->
  <xacro:property name="track_width" value="0.30"/>            <!-- Total left-right wheel separation -->
  <xacro:property name="wheelbase" value="0.18"/>              <!-- Total front-back wheel separation -->
  
  <!-- Base dimensions -->
  <xacro:property name="base_length" value="0.35"/>
  <xacro:property name="base_width" value="0.25"/>
  <xacro:property name="base_height" value="0.10"/>
  <xacro:property name="base_mass" value="8.5"/>
  
  <!-- Sensor positions -->
  <xacro:property name="lidar_height" value="0.0"/>
  <xacro:property name="camera_height" value="0.02"/>

  <!-- Inertia macros -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
             iyy="${m*(x*x+z*z)/12}" iyz="0"
             izz="${m*(x*x+y*y)/12}"/>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
             iyy="${m*(3*r*r+h*h)/12}" iyz="0"
             izz="${m*r*r/2}"/>
  </xacro:macro>

  <!-- Base footprint -->
  <link name="base_footprint"/>

  <!-- Base joint -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="chassis_material">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </inertial>
  </link>

  <!-- Mecanum wheel macro -->
  <xacro:macro name="mecanum_wheel" params="prefix x_pos y_pos rpy_val mesh_file">
    
    <!-- Wheel joint -->
    <joint name="wheel_${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="wheel_${prefix}_link"/>
      <origin xyz="${x_pos} ${y_pos} 0.0" rpy="${rpy_val}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Wheel link -->
    <link name="wheel_${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://orbibot_description/meshes/${mesh_file}" scale="1.0 1.0 1.0"/>
        </geometry>
        <material name="wheel_material">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="0.05"/>
      </inertial>
    </link>

  </xacro:macro>

  <!-- Create all wheels using the macro -->
  <xacro:mecanum_wheel prefix="front_left"  x_pos="${wheelbase/2}"  y_pos="${track_width/2}"  rpy_val="-1.57 0 0" mesh_file="mechanical-wheel-FrontLeft-BackRright.stl"/>
  <xacro:mecanum_wheel prefix="front_right" x_pos="${wheelbase/2}"  y_pos="${-track_width/2}" rpy_val="1.57 0 0"  mesh_file="mechanical-wheel-FrontRight-BackLeft.stl"/>
  <xacro:mecanum_wheel prefix="rear_right"  x_pos="${-wheelbase/2}" y_pos="${-track_width/2}" rpy_val="1.57 0 0"  mesh_file="mechanical-wheel-FrontLeft-BackRright.stl"/>
  <xacro:mecanum_wheel prefix="rear_left"   x_pos="${-wheelbase/2}" y_pos="${track_width/2}"  rpy_val="-1.57 0 0" mesh_file="mechanical-wheel-FrontRight-BackLeft.stl"/>

  <!-- RPLIDAR A1 -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.0 0.0 ${lidar_height}" rpy="${PI/2} 0 ${PI}"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <origin xyz="-0.03 0 -0.1" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://orbibot_description/meshes/RPLider-A1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="lidar_material">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.035" length="0.04"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <xacro:cylinder_inertia m="0.2" r="0.035" h="0.04"/>
    </inertial>
  </link>

  <!-- Intel RealSense D435 -->
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_length/2} 0.0 ${camera_height}" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.025 0.025"/>
      </geometry>
      <material name="camera_material">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.09 0.025 0.025"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.072"/>
      <xacro:box_inertia m="0.072" x="0.09" y="0.025" z="0.025"/>
    </inertial>
  </link>

  <!-- Camera optical frames for RealSense -->
  <joint name="camera_color_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_color_frame"/>
    <origin xyz="0.0 -0.046 0.004" rpy="0 0 0"/>
  </joint>
  <link name="camera_color_frame"/>

  <joint name="camera_color_optical_joint" type="fixed">
    <parent link="camera_color_frame"/>
    <child link="camera_color_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
  </joint>
  <link name="camera_color_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
    <origin xyz="0.0 -0.0175 0.004" rpy="0 0 0"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

  <!-- IMU sensor -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0.0 0.02" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.015 0.005"/>
      </geometry>
      <material name="imu_material">
        <color rgba="0.0 0.8 0.0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.015 0.005"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.005"/>
      <xacro:box_inertia m="0.005" x="0.015" y="0.015" z="0.005"/>
    </inertial>
  </link>

</robot>